name: Create Release Branch

on:
  workflow_dispatch:

jobs:
  create_branch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get current date
        id: date
        run: echo "TODAY=$(TZ='Asia/Tokyo' date +'%Y%m%d')" >> $GITHUB_OUTPUT # JSTのYYYYMMDD形式で日付を取得する

      - name: Create and push release branch
        run: |
          BRANCH_NAME="release/${{ steps.date.outputs.TODAY }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}