name: Trigger Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: show github sha
        run: echo $GITHUB_SHA
    
      - name: get github repository
        run: echo $GITHUB_REPOSITORY

      - name: get PR head sha
        if: github.ref == 'refs/heads/main'
        run: |
          gh_pr_head_sha=$(gh api repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/pulls | jq '.[0].head.sha')
          echo gh_pr_head_sha=$gh_pr_head_sha >> "$GITHUB_OUTPUT"
      
      - name: output PR head sha
        if: github.ref == 'refs/heads/main'
        run: echo ${{steps.get-pr-head-sha.outputs.gh_pr_head_sha}}